### ISSUE TITLE
try ACMM+ACMP

### ISSUE THREAD

**Issue by CanCanZeng** [DiantaoTu/ACMH-ACMM#5]
Hi, thank you for sharing this code, I find it very useful to understand the original paper.
Do you know the author opened their code? https://github.com/GhiXu/ACMM
And he also opened ACMP, he said that combine ACMM and ACMP may get even better result, do you interseted in implementing it?

**Comment by DiantaoTu** [comment]
I am currently focusing on LOAM, so I don't have much time on implementing ACMM+ACMP. But the author opened ACMMP (https://github.com/GhiXu/ACMMP). That's may be the combination of ACMM and ACMP.

**Comment by CanCanZeng** [comment]
Wow, it just opened 1 hour when you find it!
